spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED}

app:
  wallet:
    max-overdraft: ${APP_WALLET_MAX_OVERDRAFT}

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:postgresql:17.5-alpine:///test
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
